### PR TITLE
added the missing api/

### PR DESCRIPTION
**Pull request by qvalentin**
so this should map the following
 /api/v1/user -> /api/v1/user

you will just need to change the health endpoint @open-schnick

### CODE REVIEW

**Comment by open-schnick** [comment]
@qvalentin i need to test this locally.

**Comment by qvalentin** [comment]
> @qvalentin i need to test this locally.

You know how to do this?

**Comment by open-schnick** [comment]
It appears that swagger-ui thinks it is hosted under port 80 because it requests: `http://filefighter.ddns.net/api/v1/users/login
` and not `http://filefighter.ddns.net:3001/api/v1/users/login
`

**Review by open-schnick — APPROVED** [review]
i would approve this. its already running on production

**Pull request merged**
